"use client";

import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Calendar } from "@/components/ui/calendar";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Badge } from "@/components/ui/badge";
import { Calendar as CalendarIcon, Copy, CheckCircle2, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";
import { format } from "date-fns";
import type { Person, Ministry, ServiceType } from "@/lib/types";
import { MINISTRIES, SERVICE_TYPES } from "@/lib/constants";

interface ScheduleGeneratorProps {
  people: Person[];
}

interface Assignment {
  ministry: Ministry;
  personId: string | null;
}

export function ScheduleGenerator({ people }: ScheduleGeneratorProps) {
  const [date, setDate] = useState<Date>();
  const [serviceType, setServiceType] = useState<ServiceType>("sunday_morning");
  const [assignments, setAssignments] = useState<Assignment[]>(
    MINISTRIES.map((m) => ({ ministry: m.value, personId: null }))
  );
  const [generatedText, setGeneratedText] = useState("");
  const [copied, setCopied] = useState(false);

  // Get available people for a specific ministry
  const getAvailablePeople = (ministry: Ministry) => {
    return people.filter((p) => p.ministries.includes(ministry) && p.isActive);
  };

  // Update assignment
  const updateAssignment = (ministry: Ministry, personId: string | null) => {
    setAssignments(
      assignments.map((a) =>
        a.ministry === ministry ? { ...a, personId } : a
      )
    );
  };

  // Auto-assign people to ministries
  const autoAssign = () => {
    const newAssignments = assignments.map((assignment) => {
      const availablePeople = getAvailablePeople(assignment.ministry);
      if (availablePeople.length > 0) {
        // Pick a random person from available people
        const randomPerson =
          availablePeople[Math.floor(Math.random() * availablePeople.length)];
        return { ...assignment, personId: randomPerson.id };
      }
      return assignment;
    });
    setAssignments(newAssignments);
  };

  // Generate text schedule
  const generateSchedule = () => {
    if (!date) {
      alert("Please select a date");
      return;
    }

    const serviceTypeLabel =
      SERVICE_TYPES.find((s) => s.value === serviceType)?.label ||
      serviceType;

    const dateStr = format(date, "EEEE, MMMM d, yyyy");
    
    let schedule = `📅 SERVICE SCHEDULE\n`;
    schedule += `━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
    schedule += `📆 Date: ${dateStr}\n`;
    schedule += `⛪ Service: ${serviceTypeLabel}\n\n`;
    schedule += `👥 MINISTRY ASSIGNMENTS\n`;
    schedule += `━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;

    const assignedMinistries = assignments.filter((a) => a.personId);
    
    if (assignedMinistries.length === 0) {
      schedule += `No assignments yet.\n`;
    } else {
      assignedMinistries.forEach((assignment) => {
        const person = people.find((p) => p.id === assignment.personId);
        const ministryLabel =
          MINISTRIES.find((m) => m.value === assignment.ministry)?.label ||
          assignment.ministry;
        
        if (person) {
          schedule += `${ministryLabel}:\n`;
          schedule += `  • ${person.name}\n`;
          if (person.phone) {
            schedule += `    📱 ${person.phone}\n`;
          }
          schedule += `\n`;
        }
      });
    }

    schedule += `━━━━━━━━━━━━━━━━━━━━━━━━\n`;
    schedule += `Generated by ServeHub\n`;

    setGeneratedText(schedule);
  };

  // Copy to clipboard
  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(generatedText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      alert("Failed to copy to clipboard");
    }
  };

  return (
    <div className="grid gap-6 lg:grid-cols-2">
      {/* Left Column - Form */}
      <div className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Schedule Details</CardTitle>
            <CardDescription>
              Select the date and service type
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Date Picker */}
            <div className="space-y-2">
              <Label>Service Date</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    variant="outline"
                    className={cn(
                      "w-full justify-start text-left font-normal",
                      !date && "text-muted-foreground"
                    )}
                  >
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {date ? format(date, "PPP") : "Pick a date"}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={date}
                    onSelect={setDate}
                    initialFocus
                  />
                </PopoverContent>
              </Popover>
            </div>

            {/* Service Type */}
            <div className="space-y-2">
              <Label>Service Type</Label>
              <Select
                value={serviceType}
                onValueChange={(value) => setServiceType(value as ServiceType)}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {SERVICE_TYPES.map((type) => (
                    <SelectItem key={type.value} value={type.value}>
                      {type.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>

        {/* Ministry Assignments */}
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>Ministry Assignments</CardTitle>
                <CardDescription>
                  Assign people to each ministry
                </CardDescription>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={autoAssign}
                className="gap-2"
              >
                <Sparkles className="w-4 h-4" />
                Auto-assign
              </Button>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            {MINISTRIES.map((ministry) => {
              const assignment = assignments.find(
                (a) => a.ministry === ministry.value
              );
              const availablePeople = getAvailablePeople(ministry.value);

              return (
                <div key={ministry.value} className="space-y-2">
                  <Label htmlFor={`ministry-${ministry.value}`}>
                    {ministry.label}
                    <Badge variant="secondary" className="ml-2 text-xs">
                      {availablePeople.length} available
                    </Badge>
                  </Label>
                  <Select
                    value={assignment?.personId || "none"}
                    onValueChange={(value) =>
                      updateAssignment(
                        ministry.value,
                        value === "none" ? null : value
                      )
                    }
                  >
                    <SelectTrigger id={`ministry-${ministry.value}`}>
                      <SelectValue placeholder="Select person" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="none">
                        <span className="text-muted-foreground">
                          No assignment
                        </span>
                      </SelectItem>
                      {availablePeople.map((person) => (
                        <SelectItem key={person.id} value={person.id}>
                          {person.name}
                        </SelectItem>
                      ))}
                      {availablePeople.length === 0 && (
                        <SelectItem value="no-people" disabled>
                          No people available for this ministry
                        </SelectItem>
                      )}
                    </SelectContent>
                  </Select>
                </div>
              );
            })}
          </CardContent>
        </Card>

        <Button onClick={generateSchedule} className="w-full" size="lg">
          Generate Schedule
        </Button>
      </div>

      {/* Right Column - Generated Output */}
      <div className="space-y-6">
        <Card className="lg:sticky lg:top-6">
          <CardHeader>
            <CardTitle>Generated Schedule</CardTitle>
            <CardDescription>
              Copy this to share with your team
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {generatedText ? (
              <>
                <Textarea
                  value={generatedText}
                  readOnly
                  className="min-h-[400px] font-mono text-sm resize-none"
                />
                <Button
                  onClick={copyToClipboard}
                  className="w-full"
                  variant={copied ? "default" : "outline"}
                >
                  {copied ? (
                    <>
                      <CheckCircle2 className="w-4 h-4 mr-2" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4 mr-2" />
                      Copy to Clipboard
                    </>
                  )}
                </Button>
              </>
            ) : (
              <div className="flex flex-col items-center justify-center py-12 text-center border-2 border-dashed rounded-lg">
                <CalendarIcon className="w-12 h-12 text-muted-foreground/50 mb-4" />
                <p className="text-sm text-muted-foreground">
                  Fill in the details and click &quot;Generate Schedule&quot; to
                  create your service schedule
                </p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

